name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo ${{github.token}} | rev
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
